# Generated by Django 5.1.1 on 2024-09-18 11:32

import django.db.models.expressions
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_chat', '0005_alter_groupmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='groupmessage',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='groupchat_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='users_online',
            field=models.ManyToManyField(blank=True, related_name='users_in_online', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
